name: Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
      - run: uv sync
      - run: uv run ruff check
      - run: uv run pytest
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          docker build -t ghcr.io/jakoblui-works/site-api:${{ github.sha }} -t ghcr.io/jakoblui-works/site-api:latest .
          docker push ghcr.io/jakoblui-works/site-api:${{ github.sha }}
          docker push ghcr.io/jakoblui-works/site-api:latest
